services:
  U-CAN:
    container_name: cant5
    build:
      context: .
      dockerfile: Dockerfile.can
      args:
       USERNAME: ${USERNAME}
    image: ubuntu-can:1.0.5
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    volumes:
      - ./can:/home/${USERNAME}/can
      - /lib/modules:/lib/modules:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/${SERIAL_PORT}:/dev/${SERIAL_PORT}
      - /dev/can0:/dev/can0
    tty: true
    stdin_open: true
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: bash
        #command: [bash, "-c", "sudo ip link add dev vcan0 type vcan && sudo ip link set up vcan0 && tail -f /dev/null"]
  ROS:
    build: 
     context: .
     dockerfile: Dockerfile.ros
     args:
       USERNAME: ${USERNAME}
    image: my-ros:1.0.5
    container_name: can-ros
    volumes:
      - ./ros/sensores:/home/${USERNAME}/ros2_ws/src/
      - ./ros/data:/home/${USERNAME}/ros2_ws/src/data
    devices:
      - /dev/${SERIAL_PORT}:/dev/${SERIAL_PORT}
    privileged: true
    network_mode: "host"
    tty: true
    stdin_open: true
    command: bash
