services:
  U-CAN:
    container_name: can
    build:
      context: .
      args:
       USERNAME: ${USERNAME}
    image: ubuntu-can
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    volumes:
      - ./can:/home/${USERNAME}/can
      - /lib/modules:/lib/modules:ro
      - /tmp/.X11-unix:/tmp/.X11-unix

    tty: true
    stdin_open: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: bash

