services:
  ROS:
    build: 
     context: .
     args:
       UID: ${UID}
       GID: ${GID}
       USERNAME: ${USERNAME}
    image: my-ros:1.0.1
    container_name: ros2_ws
    volumes:
      - ./sensores:/home/${USERNAME}/ros2_ws/src/
      - ./data:/home/${USERNAME}/ros2_ws/src/data
    networks:
      rosnet:
        ipv4_address: 20.10.10.5 
    tty: true
    stdin_open: true
    command: bash
    depends_on: 
      - net-shoot

  net-shoot:
    image: nicolaka/netshoot
    container_name: netshoot
    networks:
      rosnet:
        ipv4_address: 20.10.10.100
    volumes:
      - ./netshoot:/app/pcaps
    command: ["tcpdump", "-i", "eth0", "-G", "300", "-W", "1", "-w", "/app/pcaps/trafico_ros2_%Y-%m-%d_%H-%M-%S.pcap"]
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  rosnet:
    driver: bridge
    ipam:
      config:
        - subnet: 20.10.10.0/24
          gateway: 20.10.10.1

